---
- name: create system group
  group:
    name: "{{ consul_exporter_system_group }}"
    system: true
    state: present
  when: consul_exporter_system_group != "root"
  become: true
  tags: consul_exporter

- name: create system user
  user:
    name: "{{ consul_exporter_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ consul_exporter_system_group }}"
    home: /
    createhome: false
  when: consul_exporter_system_user != "root"
  become: true
  tags: consul_exporter

- name: check if is installed
  stat:
    path: "{{ consul_exporter_binary_install_dir }}/consul_exporter"
  register: __consul_exporter_is_installed
  become: true
  tags: consul_exporter

- name: get latest release
  uri:
    url: "https://api.github.com/repos/prometheus/consul_exporter/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    validate_certs: false
    user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
    password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
  environment: "{{ proxy_env }}"
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  register: _latest_release
  until: _latest_release.status == 200
  when: consul_exporter_version == "latest"
  delegate_to: localhost
  retries: 5

- name: "set version to {{ _latest_release.json.tag_name[1:] }}"
  set_fact:
    consul_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when: consul_exporter_version == "latest"
  delegate_to: localhost
  run_once: true
  become: true
  tags: consul_exporter

- name: get checksum list from github
  set_fact:
    _checksums: "{{ lookup('url', 'https://github.com/prometheus/consul_exporter/releases/download/v' + consul_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
  environment: "{{ proxy_env }}"
  run_once: true
  become: true
  tags: consul_exporter
  when: (not __consul_exporter_is_installed.stat.exists)

- name: "get checksum for {{ go_arch }} architecture"
  set_fact:
    consul_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when:
    - "('linux-' + go_arch + '.tar.gz') in item"
    - (not __consul_exporter_is_installed.stat.exists)
  become: true
  tags: consul_exporter

- name: download binary to local folder
  get_url:
    url: "https://github.com/prometheus/consul_exporter/releases/download/v{{ consul_exporter_version }}/consul_exporter-{{ consul_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    checksum: "sha256:{{ consul_exporter_checksum }}"
  environment: "{{ proxy_env }}"
  register: _download_binary
  until: _download_binary is success
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: true
  tags: consul_exporter
  when: (not __consul_exporter_is_installed.stat.exists)

- name: unpack binary
  unarchive:
    src: "/tmp/consul_exporter-{{ consul_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/consul_exporter-{{ consul_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/consul_exporter"
  delegate_to: localhost
  check_mode: false
  become: true
  tags: consul_exporter
  when: (not __consul_exporter_is_installed.stat.exists)

- name: propagate binaries
  copy:
    src: "/tmp/consul_exporter-{{ consul_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/consul_exporter"
    dest: "{{ consul_exporter_binary_install_dir }}/consul_exporter"
    mode: 0755
  notify: restart consul_exporter
  become: true
  tags: consul_exporter
  when: (not __consul_exporter_is_installed.stat.exists)

- name: copy service unit
  template:
    src: consul_exporter.service.j2
    dest: /etc/systemd/system/consul_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart consul_exporter
  become: true
  tags: consul_exporter

- name: ensure service is started and enabled
  systemd:
    daemon_reload: true
    name: consul_exporter
    state: started
    enabled: true
  become: true
  tags: consul_exporter
