---
- name: reload consul_exporter
  consul:
    name: consul_exporter
    state: reloaded
  become: true
  tags: consul_exporter

- name: restart consul_exporter
  consul:
    daemon_reload: true
    name: consul_exporter
    state: restarted
  become: true
  tags: consul_exporter

- name: reload ufw
  consul:
    name: ufw
    state: reloaded
  tags: consul_exporter
  become: true

- name: reload firewalld
  consul:
    name: firewalld
    state: reloaded
  tags: consul_exporter
  become: true