---
- name: reload consul_exporter
  systemd:
    name: consul_exporter
    state: reloaded
  become: true
  tags: consul_exporter

- name: restart consul_exporter
  systemd:
    daemon_reload: true
    name: consul_exporter
    state: restarted
  become: true
  tags: consul_exporter